### ISSUE TITLE
Create directories for Go, NodeJs, PHP, and Python 

### ISSUE THREAD

**Issue by troy0820** [757colorcoded/server4ways#1]
### Create directories for each language for the server to go in.

Each directory should have the following files:

- [ ] README.md
- [ ] server.{language extension} _i.e server.go, server.php, server.py, server.js_
- [ ] Dependecies 

Fork this repository and layout the structure for the repository to contribute.

**Comment by dgupta04** [comment]
Hey, I'd like to work on this

**Comment by troy0820** [comment]
Go for it
