### ISSUE TITLE
Add eslint to nodejs and install pre-commit 

### ISSUE THREAD

**Issue by troy0820** [757colorcoded/server4ways#14]
### Add eslint to repository 

- [ ] Add eslint to repo
- [ ] Add `npm run lint` to scripts part in  package.json
- [ ] Add `precommit` in package.json that includes `npm run lint`

Use `eslint` and `pre-commit`  as `devDependencies` to help developers have a great experience.  recommended eslint configs `airbnb`.

**Comment by Gobinath-Manokaran** [comment]
@troy0820  Assign this issue to me. I would like to work on this
